name: Build
on:
  push:
  workflow_dispatch:

jobs:
  json:
    runs-on: macos-latest
    
    # 1. Explicitly grant write permissions so the token can push commits
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: brew info --json
        run: |
          rm -rf Info
          mkdir -p Info
          cd Formula
          find . -type f -name "*.rb" | while read -r formula; do
            formula="${formula#./}"
            formula_name=$(basename "$formula" .rb)
            output_dir="../Info/$(dirname "$formula")"
            mkdir -p "$output_dir"
            
            brew info --json "MuntasirSZN/programs/$formula_name" | jq '.[0]? // .' > "../Info/${formula/%rb/json}"
          done

      # 2. Restore Git authentication that Homebrew stripped away
      - name: Restore Git connection
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'Generated formula JSON: `brew info --json <formula>`'
          file_pattern: Info
          branch: main
          push_options: '--set-upstream origin main'